package org.lakunu.labs;

/**
 * Processes the output generated by a lab evaluation. Output is treated as line-oriented
 * text.
 */
public interface LabOutputHandler {

    default void info(String msg) {

    }

    default void warn(String msg) {

    }

    default void error(String msg) {

    }

    default void close() {

    }

}
