CREATE TABLE COURSE (
  COURSE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  OWNER VARCHAR(128) NOT NULL,
  CREATED_AT DATETIME NOT NULL,
  CONSTRAINT UNIQUE_NAME_OWNER UNIQUE(NAME, OWNER)
);