CREATE TABLE COURSE (
  COURSE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  COURSE_NAME VARCHAR(128) NOT NULL,
  COURSE_DESCRIPTION TEXT NOT NULL,
  COURSE_OWNER VARCHAR(128) NOT NULL,
  COURSE_CREATED_AT DATETIME NOT NULL,
  CONSTRAINT UNIQUE_NAME_OWNER UNIQUE(COURSE_NAME, COURSE_OWNER)
);