CREATE TABLE COURSE (
  COURSE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  COURSE_NAME VARCHAR(128) NOT NULL,
  COURSE_DESCRIPTION VARCHAR(512) NOT NULL,
  COURSE_OWNER VARCHAR(128) NOT NULL,
  COURSE_CREATED_AT DATETIME NOT NULL,
  CONSTRAINT UNIQUE_NAME_OWNER UNIQUE(COURSE_NAME, COURSE_OWNER)
);

CREATE TABLE COURSE_USER (
  COURSE_ID BIGINT NOT NULL,
  USER_ID VARCHAR(128) NOT NULL,
  USER_ROLE INT NOT NULL,
  CONSTRAINT FK_COURSE FOREIGN KEY (COURSE_ID)
  REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);